apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-load-balancer-controller-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "events", "nodes", "pods", "secrets", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses", "ingresses/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["elbv2.k8s.aws"]
  resources: ["targetgroupbindings", "targetgroupbindings/status", "ingressclassparams"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
