apiVersion: apps/v1
kind: Deployment
metadata:
  name: neostream-api-server
spec:
  selector:
    matchLabels:
      app: neostream-api
  template:
    metadata:
      labels:
        app: neostream-api
    spec:
      containers:
      - name: neostream-api
        image: backend-neostream:v4.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env: 
        - name: MONGODB_URL
          valueFrom: 
            secretKeyRef:
              name: db_url
              key: mongo_url
        - name: REDIS_SERVER
          value: "localhost"
      - name: redis
        image: redis
        resources: 
          limits: 
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379



