apiVersion: apps/v1
kind: Deployment
metadata:
  name: neostreamapiserver
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neostreamapi
  template:
    metadata:
      labels:
        app: neostreamapi
    spec:
      imagePullSecrets:
      - name: ecr-docker-credentials
      containers:
      - name: neostreamapi
        image: 825844616809.dkr.ecr.us-east-2.amazonaws.com/backend-neostream:v17
        resources:
          # requests:
          #   memory: "256Mi"
          #   cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        ports:
        - containerPort: 4000
        env: 
        - name: MONGODB_URL
          valueFrom: 
            secretKeyRef:
              name: dburl
              key: mongo_url
        - name: REDIS_SERVER
          value: "l/Users/kushal.mohta/Downloads/Terraform/NeoStream-Terraform/ecs.tf"


