apiVersion: v1
kind: Service
metadata:
  name: neostream-api-service
spec:
  type: NodePort
  selector:
    app: neostream-api
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30100
