apiVersion: v1
kind: Service
metadata:
  name: neostreamapiservice
spec:
  type: NodePort
  selector:
    app: neostreamapi
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30100
