apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels: 
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: aws-load-balancer-controller
    spec:
      serviceAccountName: aws-eks-load-balancer-controller
      securityContext: 
        fsGroup: 1337
      containers:
      - name: controller 
        args: 
        - --cluster-name=neostream-eks
        - --ingress-class=alb
        - --aws-vpc-id=vpc-0bbe3b98882005120
        - --aws-region=us-east-2
        image: public.ecr.aws/eks/aws-load-balancer-controller:v2.4.7
        livenessProbe: 
          failureThreshold: 2
          httpGet: 
            path: /healthz
            port: 61779
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports: 
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            cpu: "100m"
            memory: "200Mi"
        volumeMounts: 
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 10
      volumes: 
      - name: cert
        secret: 
          defaultMode: 420
          secretName: aws-load-balancer-webhook-tls 
        
